[theme]
primaryColor = "#0A6ED1"
backgroundColor = "#F5F6F7"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#354A5F"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
